/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as ProtectedIndexRouteImport } from './routes/_protected/index'
import { Route as ProtectedAppsRouteImport } from './routes/_protected/apps'
import { Route as DevChatRouteImport } from './routes/dev.chat'
import { Route as DevUiRouteImport } from './routes/dev.ui'
import { Route as McpConsentRouteImport } from './routes/mcp.consent'
import { Route as ProtectedAppsAppIdRouteImport } from './routes/_protected/apps.$appId'
import { Route as DevChatIndexRouteImport } from './routes/dev.chat.index'
import { Route as ProtectedAppsAppIdTThreadIdRouteImport } from './routes/_protected/apps.$appId.t.$threadId'
import { Route as DevChatAppsAppIdTThreadIdRouteImport } from './routes/dev.chat.apps.$appId.t.$threadId'

const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedIndexRoute = ProtectedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedAppsRoute = ProtectedAppsRouteImport.update({
  id: '/apps',
  path: '/apps',
  getParentRoute: () => ProtectedRoute,
} as any)
const DevChatRoute = DevChatRouteImport.update({
  id: '/dev/chat',
  path: '/dev/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const DevUiRoute = DevUiRouteImport.update({
  id: '/dev/ui',
  path: '/dev/ui',
  getParentRoute: () => rootRouteImport,
} as any)
const McpConsentRoute = McpConsentRouteImport.update({
  id: '/mcp/consent',
  path: '/mcp/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedAppsAppIdRoute = ProtectedAppsAppIdRouteImport.update({
  id: '/$appId',
  path: '/$appId',
  getParentRoute: () => ProtectedAppsRoute,
} as any)
const DevChatIndexRoute = DevChatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DevChatRoute,
} as any)
const ProtectedAppsAppIdTThreadIdRoute =
  ProtectedAppsAppIdTThreadIdRouteImport.update({
    id: '/t/$threadId',
    path: '/t/$threadId',
    getParentRoute: () => ProtectedAppsAppIdRoute,
  } as any)
const DevChatAppsAppIdTThreadIdRoute =
  DevChatAppsAppIdTThreadIdRouteImport.update({
    id: '/apps/$appId/t/$threadId',
    path: '/apps/$appId/t/$threadId',
    getParentRoute: () => DevChatRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof ProtectedIndexRoute
  '/chat': typeof ChatRoute
  '/sign-in': typeof SignInRoute
  '/signin': typeof SigninRoute
  '/apps': typeof ProtectedAppsRouteWithChildren
  '/dev/chat': typeof DevChatRouteWithChildren
  '/dev/ui': typeof DevUiRoute
  '/mcp/consent': typeof McpConsentRoute
  '/apps/$appId': typeof ProtectedAppsAppIdRouteWithChildren
  '/dev/chat/': typeof DevChatIndexRoute
  '/apps/$appId/t/$threadId': typeof ProtectedAppsAppIdTThreadIdRoute
  '/dev/chat/apps/$appId/t/$threadId': typeof DevChatAppsAppIdTThreadIdRoute
}
export interface FileRoutesByTo {
  '/chat': typeof ChatRoute
  '/sign-in': typeof SignInRoute
  '/signin': typeof SigninRoute
  '/apps': typeof ProtectedAppsRouteWithChildren
  '/dev/ui': typeof DevUiRoute
  '/mcp/consent': typeof McpConsentRoute
  '/': typeof ProtectedIndexRoute
  '/apps/$appId': typeof ProtectedAppsAppIdRouteWithChildren
  '/dev/chat': typeof DevChatIndexRoute
  '/apps/$appId/t/$threadId': typeof ProtectedAppsAppIdTThreadIdRoute
  '/dev/chat/apps/$appId/t/$threadId': typeof DevChatAppsAppIdTThreadIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_protected': typeof ProtectedRouteWithChildren
  '/chat': typeof ChatRoute
  '/sign-in': typeof SignInRoute
  '/signin': typeof SigninRoute
  '/_protected/apps': typeof ProtectedAppsRouteWithChildren
  '/dev/chat': typeof DevChatRouteWithChildren
  '/dev/ui': typeof DevUiRoute
  '/mcp/consent': typeof McpConsentRoute
  '/_protected/': typeof ProtectedIndexRoute
  '/_protected/apps/$appId': typeof ProtectedAppsAppIdRouteWithChildren
  '/dev/chat/': typeof DevChatIndexRoute
  '/_protected/apps/$appId/t/$threadId': typeof ProtectedAppsAppIdTThreadIdRoute
  '/dev/chat/apps/$appId/t/$threadId': typeof DevChatAppsAppIdTThreadIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chat'
    | '/sign-in'
    | '/signin'
    | '/apps'
    | '/dev/chat'
    | '/dev/ui'
    | '/mcp/consent'
    | '/apps/$appId'
    | '/dev/chat/'
    | '/apps/$appId/t/$threadId'
    | '/dev/chat/apps/$appId/t/$threadId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/chat'
    | '/sign-in'
    | '/signin'
    | '/apps'
    | '/dev/ui'
    | '/mcp/consent'
    | '/'
    | '/apps/$appId'
    | '/dev/chat'
    | '/apps/$appId/t/$threadId'
    | '/dev/chat/apps/$appId/t/$threadId'
  id:
    | '__root__'
    | '/_protected'
    | '/chat'
    | '/sign-in'
    | '/signin'
    | '/_protected/apps'
    | '/dev/chat'
    | '/dev/ui'
    | '/mcp/consent'
    | '/_protected/'
    | '/_protected/apps/$appId'
    | '/dev/chat/'
    | '/_protected/apps/$appId/t/$threadId'
    | '/dev/chat/apps/$appId/t/$threadId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ProtectedRoute: typeof ProtectedRouteWithChildren
  ChatRoute: typeof ChatRoute
  SignInRoute: typeof SignInRoute
  SigninRoute: typeof SigninRoute
  DevChatRoute: typeof DevChatRouteWithChildren
  DevUiRoute: typeof DevUiRoute
  McpConsentRoute: typeof McpConsentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/': {
      id: '/_protected/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ProtectedIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/apps': {
      id: '/_protected/apps'
      path: '/apps'
      fullPath: '/apps'
      preLoaderRoute: typeof ProtectedAppsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/dev/chat': {
      id: '/dev/chat'
      path: '/dev/chat'
      fullPath: '/dev/chat'
      preLoaderRoute: typeof DevChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/ui': {
      id: '/dev/ui'
      path: '/dev/ui'
      fullPath: '/dev/ui'
      preLoaderRoute: typeof DevUiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp/consent': {
      id: '/mcp/consent'
      path: '/mcp/consent'
      fullPath: '/mcp/consent'
      preLoaderRoute: typeof McpConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/apps/$appId': {
      id: '/_protected/apps/$appId'
      path: '/$appId'
      fullPath: '/apps/$appId'
      preLoaderRoute: typeof ProtectedAppsAppIdRouteImport
      parentRoute: typeof ProtectedAppsRoute
    }
    '/dev/chat/': {
      id: '/dev/chat/'
      path: '/'
      fullPath: '/dev/chat/'
      preLoaderRoute: typeof DevChatIndexRouteImport
      parentRoute: typeof DevChatRoute
    }
    '/_protected/apps/$appId/t/$threadId': {
      id: '/_protected/apps/$appId/t/$threadId'
      path: '/t/$threadId'
      fullPath: '/apps/$appId/t/$threadId'
      preLoaderRoute: typeof ProtectedAppsAppIdTThreadIdRouteImport
      parentRoute: typeof ProtectedAppsAppIdRoute
    }
    '/dev/chat/apps/$appId/t/$threadId': {
      id: '/dev/chat/apps/$appId/t/$threadId'
      path: '/apps/$appId/t/$threadId'
      fullPath: '/dev/chat/apps/$appId/t/$threadId'
      preLoaderRoute: typeof DevChatAppsAppIdTThreadIdRouteImport
      parentRoute: typeof DevChatRoute
    }
  }
}

interface ProtectedAppsAppIdRouteChildren {
  ProtectedAppsAppIdTThreadIdRoute: typeof ProtectedAppsAppIdTThreadIdRoute
}

const ProtectedAppsAppIdRouteChildren: ProtectedAppsAppIdRouteChildren = {
  ProtectedAppsAppIdTThreadIdRoute: ProtectedAppsAppIdTThreadIdRoute,
}

const ProtectedAppsAppIdRouteWithChildren =
  ProtectedAppsAppIdRoute._addFileChildren(ProtectedAppsAppIdRouteChildren)

interface ProtectedAppsRouteChildren {
  ProtectedAppsAppIdRoute: typeof ProtectedAppsAppIdRouteWithChildren
}

const ProtectedAppsRouteChildren: ProtectedAppsRouteChildren = {
  ProtectedAppsAppIdRoute: ProtectedAppsAppIdRouteWithChildren,
}

const ProtectedAppsRouteWithChildren = ProtectedAppsRoute._addFileChildren(
  ProtectedAppsRouteChildren,
)

interface ProtectedRouteChildren {
  ProtectedAppsRoute: typeof ProtectedAppsRouteWithChildren
  ProtectedIndexRoute: typeof ProtectedIndexRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedAppsRoute: ProtectedAppsRouteWithChildren,
  ProtectedIndexRoute: ProtectedIndexRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

interface DevChatRouteChildren {
  DevChatIndexRoute: typeof DevChatIndexRoute
  DevChatAppsAppIdTThreadIdRoute: typeof DevChatAppsAppIdTThreadIdRoute
}

const DevChatRouteChildren: DevChatRouteChildren = {
  DevChatIndexRoute: DevChatIndexRoute,
  DevChatAppsAppIdTThreadIdRoute: DevChatAppsAppIdTThreadIdRoute,
}

const DevChatRouteWithChildren =
  DevChatRoute._addFileChildren(DevChatRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ProtectedRoute: ProtectedRouteWithChildren,
  ChatRoute: ChatRoute,
  SignInRoute: SignInRoute,
  SigninRoute: SigninRoute,
  DevChatRoute: DevChatRouteWithChildren,
  DevUiRoute: DevUiRoute,
  McpConsentRoute: McpConsentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
