/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as ProtectedIndexRouteImport } from './routes/_protected/index'
import { Route as McpConsentRouteImport } from './routes/mcp.consent'
import { Route as DevUiRouteImport } from './routes/dev.ui'
import { Route as DevChatRouteImport } from './routes/dev.chat'
import { Route as ProtectedAppsRouteImport } from './routes/_protected/apps'
import { Route as DevChatIndexRouteImport } from './routes/dev.chat.index'
import { Route as ProtectedAppsIndexRouteImport } from './routes/_protected/apps.index'
import { Route as ProtectedAppsAppIdRouteImport } from './routes/_protected/apps.$appId'
import { Route as ProtectedAppsAppIdIndexRouteImport } from './routes/_protected/apps.$appId.index'
import { Route as ProtectedAppsAppIdPreviewRouteImport } from './routes/_protected/apps.$appId.preview'
import { Route as ProtectedAppsAppIdPrsRouteImport } from './routes/_protected/apps.$appId.prs'
import { Route as ProtectedAppsAppIdPrsIndexRouteImport } from './routes/_protected/apps.$appId.prs.index'
import { Route as ProtectedAppsAppIdPrsPrNumberRouteImport } from './routes/_protected/apps.$appId.prs.$prNumber'
import { Route as ProtectedAppsAppIdTThreadIdRouteImport } from './routes/_protected/apps.$appId.t.$threadId'
import { Route as DevChatAppsAppIdTThreadIdRouteImport } from './routes/dev.chat.apps.$appId.t.$threadId'

const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedIndexRoute = ProtectedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedRoute,
} as any)
const McpConsentRoute = McpConsentRouteImport.update({
  id: '/mcp/consent',
  path: '/mcp/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const DevUiRoute = DevUiRouteImport.update({
  id: '/dev/ui',
  path: '/dev/ui',
  getParentRoute: () => rootRouteImport,
} as any)
const DevChatRoute = DevChatRouteImport.update({
  id: '/dev/chat',
  path: '/dev/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedAppsRoute = ProtectedAppsRouteImport.update({
  id: '/apps',
  path: '/apps',
  getParentRoute: () => ProtectedRoute,
} as any)
const DevChatIndexRoute = DevChatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DevChatRoute,
} as any)
const ProtectedAppsIndexRoute = ProtectedAppsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedAppsRoute,
} as any)
const ProtectedAppsAppIdRoute = ProtectedAppsAppIdRouteImport.update({
  id: '/$appId',
  path: '/$appId',
  getParentRoute: () => ProtectedAppsRoute,
} as any)
const ProtectedAppsAppIdIndexRoute = ProtectedAppsAppIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedAppsAppIdRoute,
} as any)
const ProtectedAppsAppIdPreviewRoute =
  ProtectedAppsAppIdPreviewRouteImport.update({
    id: '/preview',
    path: '/preview',
    getParentRoute: () => ProtectedAppsAppIdRoute,
  } as any)
const ProtectedAppsAppIdPrsRoute = ProtectedAppsAppIdPrsRouteImport.update({
  id: '/prs',
  path: '/prs',
  getParentRoute: () => ProtectedAppsAppIdRoute,
} as any)
const ProtectedAppsAppIdPrsIndexRoute =
  ProtectedAppsAppIdPrsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProtectedAppsAppIdPrsRoute,
  } as any)
const ProtectedAppsAppIdPrsPrNumberRoute =
  ProtectedAppsAppIdPrsPrNumberRouteImport.update({
    id: '/$prNumber',
    path: '/$prNumber',
    getParentRoute: () => ProtectedAppsAppIdPrsRoute,
  } as any)
const ProtectedAppsAppIdTThreadIdRoute =
  ProtectedAppsAppIdTThreadIdRouteImport.update({
    id: '/t/$threadId',
    path: '/t/$threadId',
    getParentRoute: () => ProtectedAppsAppIdRoute,
  } as any)
const DevChatAppsAppIdTThreadIdRoute =
  DevChatAppsAppIdTThreadIdRouteImport.update({
    id: '/apps/$appId/t/$threadId',
    path: '/apps/$appId/t/$threadId',
    getParentRoute: () => DevChatRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof ProtectedIndexRoute
  '/chat': typeof ChatRoute
  '/sign-in': typeof SignInRoute
  '/signin': typeof SigninRoute
  '/apps': typeof ProtectedAppsRouteWithChildren
  '/dev/chat': typeof DevChatRouteWithChildren
  '/dev/ui': typeof DevUiRoute
  '/mcp/consent': typeof McpConsentRoute
  '/apps/$appId': typeof ProtectedAppsAppIdRouteWithChildren
  '/apps/': typeof ProtectedAppsIndexRoute
  '/dev/chat/': typeof DevChatIndexRoute
  '/apps/$appId/': typeof ProtectedAppsAppIdIndexRoute
  '/apps/$appId/preview': typeof ProtectedAppsAppIdPreviewRoute
  '/apps/$appId/prs': typeof ProtectedAppsAppIdPrsRouteWithChildren
  '/apps/$appId/prs/': typeof ProtectedAppsAppIdPrsIndexRoute
  '/apps/$appId/prs/$prNumber': typeof ProtectedAppsAppIdPrsPrNumberRoute
  '/apps/$appId/t/$threadId': typeof ProtectedAppsAppIdTThreadIdRoute
  '/dev/chat/apps/$appId/t/$threadId': typeof DevChatAppsAppIdTThreadIdRoute
}
export interface FileRoutesByTo {
  '/chat': typeof ChatRoute
  '/sign-in': typeof SignInRoute
  '/signin': typeof SigninRoute
  '/dev/ui': typeof DevUiRoute
  '/mcp/consent': typeof McpConsentRoute
  '/': typeof ProtectedIndexRoute
  '/apps': typeof ProtectedAppsIndexRoute
  '/dev/chat': typeof DevChatIndexRoute
  '/apps/$appId': typeof ProtectedAppsAppIdIndexRoute
  '/apps/$appId/preview': typeof ProtectedAppsAppIdPreviewRoute
  '/apps/$appId/prs': typeof ProtectedAppsAppIdPrsIndexRoute
  '/apps/$appId/prs/$prNumber': typeof ProtectedAppsAppIdPrsPrNumberRoute
  '/apps/$appId/t/$threadId': typeof ProtectedAppsAppIdTThreadIdRoute
  '/dev/chat/apps/$appId/t/$threadId': typeof DevChatAppsAppIdTThreadIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_protected': typeof ProtectedRouteWithChildren
  '/chat': typeof ChatRoute
  '/sign-in': typeof SignInRoute
  '/signin': typeof SigninRoute
  '/_protected/apps': typeof ProtectedAppsRouteWithChildren
  '/dev/chat': typeof DevChatRouteWithChildren
  '/dev/ui': typeof DevUiRoute
  '/mcp/consent': typeof McpConsentRoute
  '/_protected/': typeof ProtectedIndexRoute
  '/_protected/apps/$appId': typeof ProtectedAppsAppIdRouteWithChildren
  '/_protected/apps/': typeof ProtectedAppsIndexRoute
  '/dev/chat/': typeof DevChatIndexRoute
  '/_protected/apps/$appId/': typeof ProtectedAppsAppIdIndexRoute
  '/_protected/apps/$appId/preview': typeof ProtectedAppsAppIdPreviewRoute
  '/_protected/apps/$appId/prs': typeof ProtectedAppsAppIdPrsRouteWithChildren
  '/_protected/apps/$appId/prs/': typeof ProtectedAppsAppIdPrsIndexRoute
  '/_protected/apps/$appId/prs/$prNumber': typeof ProtectedAppsAppIdPrsPrNumberRoute
  '/_protected/apps/$appId/t/$threadId': typeof ProtectedAppsAppIdTThreadIdRoute
  '/dev/chat/apps/$appId/t/$threadId': typeof DevChatAppsAppIdTThreadIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chat'
    | '/sign-in'
    | '/signin'
    | '/apps'
    | '/dev/chat'
    | '/dev/ui'
    | '/mcp/consent'
    | '/apps/$appId'
    | '/apps/'
    | '/dev/chat/'
    | '/apps/$appId/'
    | '/apps/$appId/preview'
    | '/apps/$appId/prs'
    | '/apps/$appId/prs/'
    | '/apps/$appId/prs/$prNumber'
    | '/apps/$appId/t/$threadId'
    | '/dev/chat/apps/$appId/t/$threadId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/chat'
    | '/sign-in'
    | '/signin'
    | '/dev/ui'
    | '/mcp/consent'
    | '/'
    | '/apps'
    | '/dev/chat'
    | '/apps/$appId'
    | '/apps/$appId/preview'
    | '/apps/$appId/prs'
    | '/apps/$appId/prs/$prNumber'
    | '/apps/$appId/t/$threadId'
    | '/dev/chat/apps/$appId/t/$threadId'
  id:
    | '__root__'
    | '/_protected'
    | '/chat'
    | '/sign-in'
    | '/signin'
    | '/_protected/apps'
    | '/dev/chat'
    | '/dev/ui'
    | '/mcp/consent'
    | '/_protected/'
    | '/_protected/apps/$appId'
    | '/_protected/apps/'
    | '/dev/chat/'
    | '/_protected/apps/$appId/'
    | '/_protected/apps/$appId/preview'
    | '/_protected/apps/$appId/prs'
    | '/_protected/apps/$appId/prs/'
    | '/_protected/apps/$appId/prs/$prNumber'
    | '/_protected/apps/$appId/t/$threadId'
    | '/dev/chat/apps/$appId/t/$threadId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ProtectedRoute: typeof ProtectedRouteWithChildren
  ChatRoute: typeof ChatRoute
  SignInRoute: typeof SignInRoute
  SigninRoute: typeof SigninRoute
  DevChatRoute: typeof DevChatRouteWithChildren
  DevUiRoute: typeof DevUiRoute
  McpConsentRoute: typeof McpConsentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/': {
      id: '/_protected/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ProtectedIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/mcp/consent': {
      id: '/mcp/consent'
      path: '/mcp/consent'
      fullPath: '/mcp/consent'
      preLoaderRoute: typeof McpConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/ui': {
      id: '/dev/ui'
      path: '/dev/ui'
      fullPath: '/dev/ui'
      preLoaderRoute: typeof DevUiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/chat': {
      id: '/dev/chat'
      path: '/dev/chat'
      fullPath: '/dev/chat'
      preLoaderRoute: typeof DevChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/apps': {
      id: '/_protected/apps'
      path: '/apps'
      fullPath: '/apps'
      preLoaderRoute: typeof ProtectedAppsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/dev/chat/': {
      id: '/dev/chat/'
      path: '/'
      fullPath: '/dev/chat/'
      preLoaderRoute: typeof DevChatIndexRouteImport
      parentRoute: typeof DevChatRoute
    }
    '/_protected/apps/': {
      id: '/_protected/apps/'
      path: '/'
      fullPath: '/apps/'
      preLoaderRoute: typeof ProtectedAppsIndexRouteImport
      parentRoute: typeof ProtectedAppsRoute
    }
    '/_protected/apps/$appId': {
      id: '/_protected/apps/$appId'
      path: '/$appId'
      fullPath: '/apps/$appId'
      preLoaderRoute: typeof ProtectedAppsAppIdRouteImport
      parentRoute: typeof ProtectedAppsRoute
    }
    '/_protected/apps/$appId/': {
      id: '/_protected/apps/$appId/'
      path: '/'
      fullPath: '/apps/$appId/'
      preLoaderRoute: typeof ProtectedAppsAppIdIndexRouteImport
      parentRoute: typeof ProtectedAppsAppIdRoute
    }
    '/_protected/apps/$appId/preview': {
      id: '/_protected/apps/$appId/preview'
      path: '/preview'
      fullPath: '/apps/$appId/preview'
      preLoaderRoute: typeof ProtectedAppsAppIdPreviewRouteImport
      parentRoute: typeof ProtectedAppsAppIdRoute
    }
    '/_protected/apps/$appId/prs': {
      id: '/_protected/apps/$appId/prs'
      path: '/prs'
      fullPath: '/apps/$appId/prs'
      preLoaderRoute: typeof ProtectedAppsAppIdPrsRouteImport
      parentRoute: typeof ProtectedAppsAppIdRoute
    }
    '/_protected/apps/$appId/prs/': {
      id: '/_protected/apps/$appId/prs/'
      path: '/'
      fullPath: '/apps/$appId/prs/'
      preLoaderRoute: typeof ProtectedAppsAppIdPrsIndexRouteImport
      parentRoute: typeof ProtectedAppsAppIdPrsRoute
    }
    '/_protected/apps/$appId/prs/$prNumber': {
      id: '/_protected/apps/$appId/prs/$prNumber'
      path: '/$prNumber'
      fullPath: '/apps/$appId/prs/$prNumber'
      preLoaderRoute: typeof ProtectedAppsAppIdPrsPrNumberRouteImport
      parentRoute: typeof ProtectedAppsAppIdPrsRoute
    }
    '/_protected/apps/$appId/t/$threadId': {
      id: '/_protected/apps/$appId/t/$threadId'
      path: '/t/$threadId'
      fullPath: '/apps/$appId/t/$threadId'
      preLoaderRoute: typeof ProtectedAppsAppIdTThreadIdRouteImport
      parentRoute: typeof ProtectedAppsAppIdRoute
    }
    '/dev/chat/apps/$appId/t/$threadId': {
      id: '/dev/chat/apps/$appId/t/$threadId'
      path: '/apps/$appId/t/$threadId'
      fullPath: '/dev/chat/apps/$appId/t/$threadId'
      preLoaderRoute: typeof DevChatAppsAppIdTThreadIdRouteImport
      parentRoute: typeof DevChatRoute
    }
  }
}

interface ProtectedAppsAppIdPrsRouteChildren {
  ProtectedAppsAppIdPrsIndexRoute: typeof ProtectedAppsAppIdPrsIndexRoute
  ProtectedAppsAppIdPrsPrNumberRoute: typeof ProtectedAppsAppIdPrsPrNumberRoute
}

const ProtectedAppsAppIdPrsRouteChildren: ProtectedAppsAppIdPrsRouteChildren = {
  ProtectedAppsAppIdPrsIndexRoute: ProtectedAppsAppIdPrsIndexRoute,
  ProtectedAppsAppIdPrsPrNumberRoute: ProtectedAppsAppIdPrsPrNumberRoute,
}

const ProtectedAppsAppIdPrsRouteWithChildren =
  ProtectedAppsAppIdPrsRoute._addFileChildren(ProtectedAppsAppIdPrsRouteChildren)

interface ProtectedAppsAppIdRouteChildren {
  ProtectedAppsAppIdIndexRoute: typeof ProtectedAppsAppIdIndexRoute
  ProtectedAppsAppIdPreviewRoute: typeof ProtectedAppsAppIdPreviewRoute
  ProtectedAppsAppIdPrsRoute: typeof ProtectedAppsAppIdPrsRouteWithChildren
  ProtectedAppsAppIdTThreadIdRoute: typeof ProtectedAppsAppIdTThreadIdRoute
}

const ProtectedAppsAppIdRouteChildren: ProtectedAppsAppIdRouteChildren = {
  ProtectedAppsAppIdIndexRoute: ProtectedAppsAppIdIndexRoute,
  ProtectedAppsAppIdPreviewRoute: ProtectedAppsAppIdPreviewRoute,
  ProtectedAppsAppIdPrsRoute: ProtectedAppsAppIdPrsRouteWithChildren,
  ProtectedAppsAppIdTThreadIdRoute: ProtectedAppsAppIdTThreadIdRoute,
}

const ProtectedAppsAppIdRouteWithChildren =
  ProtectedAppsAppIdRoute._addFileChildren(ProtectedAppsAppIdRouteChildren)

interface ProtectedAppsRouteChildren {
  ProtectedAppsAppIdRoute: typeof ProtectedAppsAppIdRouteWithChildren
  ProtectedAppsIndexRoute: typeof ProtectedAppsIndexRoute
}

const ProtectedAppsRouteChildren: ProtectedAppsRouteChildren = {
  ProtectedAppsAppIdRoute: ProtectedAppsAppIdRouteWithChildren,
  ProtectedAppsIndexRoute: ProtectedAppsIndexRoute,
}

const ProtectedAppsRouteWithChildren = ProtectedAppsRoute._addFileChildren(
  ProtectedAppsRouteChildren,
)

interface ProtectedRouteChildren {
  ProtectedAppsRoute: typeof ProtectedAppsRouteWithChildren
  ProtectedIndexRoute: typeof ProtectedIndexRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedAppsRoute: ProtectedAppsRouteWithChildren,
  ProtectedIndexRoute: ProtectedIndexRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

interface DevChatRouteChildren {
  DevChatIndexRoute: typeof DevChatIndexRoute
  DevChatAppsAppIdTThreadIdRoute: typeof DevChatAppsAppIdTThreadIdRoute
}

const DevChatRouteChildren: DevChatRouteChildren = {
  DevChatIndexRoute: DevChatIndexRoute,
  DevChatAppsAppIdTThreadIdRoute: DevChatAppsAppIdTThreadIdRoute,
}

const DevChatRouteWithChildren =
  DevChatRoute._addFileChildren(DevChatRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ProtectedRoute: ProtectedRouteWithChildren,
  ChatRoute: ChatRoute,
  SignInRoute: SignInRoute,
  SigninRoute: SigninRoute,
  DevChatRoute: DevChatRouteWithChildren,
  DevUiRoute: DevUiRoute,
  McpConsentRoute: McpConsentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
