/**
 * Embed Tailwind package CSS for in-worker compile() loadStylesheet.
 * Emits src/generated/css-vfs.js.
 */

import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { gzipSync } from "node:zlib";
import { getUniverseRequire } from "./universe.mjs";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const generatedDir = join(root, "src", "generated");
const require = getUniverseRequire();
const twRoot = dirname(require.resolve("tailwindcss/package.json"));

const files = {
  tailwindcss: "index.css",
  "tailwindcss/index": "index.css",
  "tailwindcss/index.css": "index.css",
  "tailwindcss/theme": "theme.css",
  "tailwindcss/theme.css": "theme.css",
  "tailwindcss/preflight": "preflight.css",
  "tailwindcss/preflight.css": "preflight.css",
  "tailwindcss/utilities": "utilities.css",
  "tailwindcss/utilities.css": "utilities.css",
};

/** @type {Record<string, string>} */
const vfs = {};
for (const [id, file] of Object.entries(files)) {
  vfs[id] = readFileSync(join(twRoot, file), "utf8");
}

mkdirSync(generatedDir, { recursive: true });
mkdirSync(join(root, "results"), { recursive: true });

const json = JSON.stringify(vfs);
const gzipBytes = gzipSync(Buffer.from(json)).length;
const rawBytes = Buffer.byteLength(json);

writeFileSync(
  join(generatedDir, "css-vfs.js"),
  `/** AUTO-GENERATED by packages/kernel/scripts/prebuild-css-vfs.mjs — do not edit */
export const TW_CSS_VFS = ${json};
export const TW_INDEX_CSS_BYTES = ${Buffer.byteLength(vfs.tailwindcss)};
`
);

const sizes = {
  entries: Object.keys(vfs).length,
  rawBytes,
  gzipBytes,
  twIndexCssRaw: Buffer.byteLength(vfs.tailwindcss),
};
writeFileSync(
  join(root, "results", "css-vfs-sizes.json"),
  `${JSON.stringify(sizes, null, 2)}\n`
);
console.log("css vfs", sizes);
