/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// Generated by `pnpm generate-routes` (template-only; hosted apps have no
// generator). When you add, move, or delete a file under src/routes/, edit
// this file by hand to match: the import, the route const, all three
// FileRoutesBy* interfaces, the FileRoutesByPath module augmentation, and
// the children wiring at the bottom. A route missing from the children
// wiring 404s at runtime, so mirror an existing route end to end.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as SignUpRouteImport } from "./routes/sign-up"
import { Route as SignInRouteImport } from "./routes/sign-in"
import { Route as OnboardingRouteImport } from "./routes/onboarding"
import { Route as AppRouteImport } from "./routes/_app"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as AppSettingsRouteImport } from "./routes/_app/settings"
import { Route as AppOverviewRouteImport } from "./routes/_app/overview"
import { Route as AppGalleryRouteImport } from "./routes/_app/gallery"
import { Route as AppBalancesRouteImport } from "./routes/_app/balances"
import { Route as AppPartiesIndexRouteImport } from "./routes/_app/parties/index"
import { Route as AppItemsIndexRouteImport } from "./routes/_app/items/index"
import { Route as AppInvoicesIndexRouteImport } from "./routes/_app/invoices/index"
import { Route as AppPartiesIdRouteImport } from "./routes/_app/parties/$id"
import { Route as AppInvoicesIdRouteImport } from "./routes/_app/invoices/$id"

const SignUpRoute = SignUpRouteImport.update({
  id: "/sign-up",
  path: "/sign-up",
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: "/sign-in",
  path: "/sign-in",
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: "/onboarding",
  path: "/onboarding",
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: "/_app",
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: "/settings",
  path: "/settings",
  getParentRoute: () => AppRoute,
} as any)
const AppOverviewRoute = AppOverviewRouteImport.update({
  id: "/overview",
  path: "/overview",
  getParentRoute: () => AppRoute,
} as any)
const AppGalleryRoute = AppGalleryRouteImport.update({
  id: "/gallery",
  path: "/gallery",
  getParentRoute: () => AppRoute,
} as any)
const AppBalancesRoute = AppBalancesRouteImport.update({
  id: "/balances",
  path: "/balances",
  getParentRoute: () => AppRoute,
} as any)
const AppPartiesIndexRoute = AppPartiesIndexRouteImport.update({
  id: "/parties/",
  path: "/parties/",
  getParentRoute: () => AppRoute,
} as any)
const AppItemsIndexRoute = AppItemsIndexRouteImport.update({
  id: "/items/",
  path: "/items/",
  getParentRoute: () => AppRoute,
} as any)
const AppInvoicesIndexRoute = AppInvoicesIndexRouteImport.update({
  id: "/invoices/",
  path: "/invoices/",
  getParentRoute: () => AppRoute,
} as any)
const AppPartiesIdRoute = AppPartiesIdRouteImport.update({
  id: "/parties/$id",
  path: "/parties/$id",
  getParentRoute: () => AppRoute,
} as any)
const AppInvoicesIdRoute = AppInvoicesIdRouteImport.update({
  id: "/invoices/$id",
  path: "/invoices/$id",
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/onboarding": typeof OnboardingRoute
  "/sign-in": typeof SignInRoute
  "/sign-up": typeof SignUpRoute
  "/balances": typeof AppBalancesRoute
  "/gallery": typeof AppGalleryRoute
  "/overview": typeof AppOverviewRoute
  "/settings": typeof AppSettingsRoute
  "/invoices/$id": typeof AppInvoicesIdRoute
  "/parties/$id": typeof AppPartiesIdRoute
  "/invoices": typeof AppInvoicesIndexRoute
  "/items": typeof AppItemsIndexRoute
  "/parties": typeof AppPartiesIndexRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/onboarding": typeof OnboardingRoute
  "/sign-in": typeof SignInRoute
  "/sign-up": typeof SignUpRoute
  "/balances": typeof AppBalancesRoute
  "/gallery": typeof AppGalleryRoute
  "/overview": typeof AppOverviewRoute
  "/settings": typeof AppSettingsRoute
  "/invoices/$id": typeof AppInvoicesIdRoute
  "/parties/$id": typeof AppPartiesIdRoute
  "/invoices": typeof AppInvoicesIndexRoute
  "/items": typeof AppItemsIndexRoute
  "/parties": typeof AppPartiesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/_app": typeof AppRouteWithChildren
  "/onboarding": typeof OnboardingRoute
  "/sign-in": typeof SignInRoute
  "/sign-up": typeof SignUpRoute
  "/_app/balances": typeof AppBalancesRoute
  "/_app/gallery": typeof AppGalleryRoute
  "/_app/overview": typeof AppOverviewRoute
  "/_app/settings": typeof AppSettingsRoute
  "/_app/invoices/$id": typeof AppInvoicesIdRoute
  "/_app/parties/$id": typeof AppPartiesIdRoute
  "/_app/invoices/": typeof AppInvoicesIndexRoute
  "/_app/items/": typeof AppItemsIndexRoute
  "/_app/parties/": typeof AppPartiesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/onboarding"
    | "/sign-in"
    | "/sign-up"
    | "/balances"
    | "/gallery"
    | "/overview"
    | "/settings"
    | "/invoices/$id"
    | "/parties/$id"
    | "/invoices"
    | "/items"
    | "/parties"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | "/onboarding"
    | "/sign-in"
    | "/sign-up"
    | "/balances"
    | "/gallery"
    | "/overview"
    | "/settings"
    | "/invoices/$id"
    | "/parties/$id"
    | "/invoices"
    | "/items"
    | "/parties"
  id:
    | "__root__"
    | "/"
    | "/_app"
    | "/onboarding"
    | "/sign-in"
    | "/sign-up"
    | "/_app/balances"
    | "/_app/gallery"
    | "/_app/overview"
    | "/_app/settings"
    | "/_app/invoices/$id"
    | "/_app/parties/$id"
    | "/_app/invoices/"
    | "/_app/items/"
    | "/_app/parties/"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/sign-up": {
      id: "/sign-up"
      path: "/sign-up"
      fullPath: "/sign-up"
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/sign-in": {
      id: "/sign-in"
      path: "/sign-in"
      fullPath: "/sign-in"
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/onboarding": {
      id: "/onboarding"
      path: "/onboarding"
      fullPath: "/onboarding"
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_app": {
      id: "/_app"
      path: ""
      fullPath: ""
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_app/settings": {
      id: "/_app/settings"
      path: "/settings"
      fullPath: "/settings"
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    "/_app/overview": {
      id: "/_app/overview"
      path: "/overview"
      fullPath: "/overview"
      preLoaderRoute: typeof AppOverviewRouteImport
      parentRoute: typeof AppRoute
    }
    "/_app/gallery": {
      id: "/_app/gallery"
      path: "/gallery"
      fullPath: "/gallery"
      preLoaderRoute: typeof AppGalleryRouteImport
      parentRoute: typeof AppRoute
    }
    "/_app/balances": {
      id: "/_app/balances"
      path: "/balances"
      fullPath: "/balances"
      preLoaderRoute: typeof AppBalancesRouteImport
      parentRoute: typeof AppRoute
    }
    "/_app/parties/": {
      id: "/_app/parties/"
      path: "/parties"
      fullPath: "/parties"
      preLoaderRoute: typeof AppPartiesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    "/_app/items/": {
      id: "/_app/items/"
      path: "/items"
      fullPath: "/items"
      preLoaderRoute: typeof AppItemsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    "/_app/invoices/": {
      id: "/_app/invoices/"
      path: "/invoices"
      fullPath: "/invoices"
      preLoaderRoute: typeof AppInvoicesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    "/_app/parties/$id": {
      id: "/_app/parties/$id"
      path: "/parties/$id"
      fullPath: "/parties/$id"
      preLoaderRoute: typeof AppPartiesIdRouteImport
      parentRoute: typeof AppRoute
    }
    "/_app/invoices/$id": {
      id: "/_app/invoices/$id"
      path: "/invoices/$id"
      fullPath: "/invoices/$id"
      preLoaderRoute: typeof AppInvoicesIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppBalancesRoute: typeof AppBalancesRoute
  AppGalleryRoute: typeof AppGalleryRoute
  AppOverviewRoute: typeof AppOverviewRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppInvoicesIdRoute: typeof AppInvoicesIdRoute
  AppPartiesIdRoute: typeof AppPartiesIdRoute
  AppInvoicesIndexRoute: typeof AppInvoicesIndexRoute
  AppItemsIndexRoute: typeof AppItemsIndexRoute
  AppPartiesIndexRoute: typeof AppPartiesIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBalancesRoute: AppBalancesRoute,
  AppGalleryRoute: AppGalleryRoute,
  AppOverviewRoute: AppOverviewRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppInvoicesIdRoute: AppInvoicesIdRoute,
  AppPartiesIdRoute: AppPartiesIdRoute,
  AppInvoicesIndexRoute: AppInvoicesIndexRoute,
  AppItemsIndexRoute: AppItemsIndexRoute,
  AppPartiesIndexRoute: AppPartiesIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
